### ISSUE TITLE
CDing to the wrong place

### ISSUE THREAD

**Issue by mawkish** [mitchpaulus/autocorrect.vim#2]
In your AutocorrectForceLoad function you're saving the previous directory with:

```
let previousDirectory = expand("%:p:h")
```

But that's not necessarily the real previous directory. You should be using getcwd().

I think I'm right about this. I keep being transported against my will into the parent directory of the file I'm editing.

**Comment by mitchpaulus** [comment]
@mawkish Thanks for pointing this out. I've made a commit that makes this change. Can you confirm this addresses the issue you were having?
