### ISSUE TITLE
Improvement: load iabbrevs async

### ISSUE THREAD

**Issue by chris-ritsen** [mitchpaulus/autocorrect.vim#3]
I had the same idea as you: use iabbrev for autocorrect.  As the list of corrections grows it takes longer to insert new abbrevs and the total time makes it inconvenient to load them with every running instance of vim. 

This is now a solved problem. Take a look at the code from [my version](https://github.com/chris-ritsen/vim-autocorrect/blob/de433387c6d82451d888e5e0c21bc2e83df1660f/opt/vim-abbrev/plugin/abbrev.vim) that uses the vim 8/nvim function `timer_start` to load the words and execute iabbrev commands asynchronously in batches at a delay.  

With this I am now using my corrections on every transient instance of vim.  My list of over 43,000 corrections loads in about 6-10 seconds without perceivably blocking user input, which is only two seconds slower than doing it while fully blocking user input.

**Comment by mitchpaulus** [comment]
Wow, 43,000 corrections is a lot! My personal list is only ~ 7,000 and so it hadn't got a point that I was noticing the load up time. 

But I took your version as inspiration and now asynchronously load these up in fedb1d90ec9a6de77c2308f54f32e6556ce9d713. 

Appreciated the help!
